name = "git-server"
version = "0.1.0"
component = "/Users/colinrozzi/work/actor-registry/git-server/./target/wasm32-unknown-unknown/release/git_server.wasm"
description = "A basic Theater actor"
save_chain = true

[[handler]]
type = "runtime"

[[handler]]
type = "http-framework"
